"use client";

import { useActionState, useEffect, useRef, useState } from "react";
import { addAccessory, type AddAccessoryState } from "./actions";
import { COLORS, DEFAULT_COLOR_ID, colorOklch } from "@/lib/colors";
import { DEVICE_TYPES, DeviceIcon } from "@/lib/device-types";

interface MemberLite {
  id: string;
  name: string;
  color: string;
  initials: string;
  title: string | null;
}

const initialState: AddAccessoryState = { ok: false };

interface ImportInfo {
  filename: string;
  // we keep the raw text and submit it via a hidden textarea so the
  // server's parseKeysText is the single source of truth for validation
  text: string;
}

export function AddAccessoryForm({ members }: { members: MemberLite[] }) {
  const [state, formAction, pending] = useActionState(addAccessory, initialState);
  const [name, setName] = useState("");
  const [type, setType] = useState("tag");
  const [color, setColor] = useState(DEFAULT_COLOR_ID);
  const [ownerIds, setOwnerIds] = useState<string[]>(
    members.length === 1 ? [members[0].id] : [],
  );
  const [primary, setPrimary] = useState<string>(
    members.length === 1 ? members[0].id : "",
  );
  const [imported, setImported] = useState<ImportInfo | null>(null);
  const [importErr, setImportErr] = useState<string | null>(null);
  const [showManual, setShowManual] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);

  // Pick up a .keys file that was drag-dropped onto /map. MapShell
  // stashes the parsed content in sessionStorage and navigates here.
  useEffect(() => {
    try {
      const raw = sessionStorage.getItem("fmf:pending-keys-import");
      if (!raw) return;
      sessionStorage.removeItem("fmf:pending-keys-import");
      const parsed = JSON.parse(raw) as { filename?: string; text?: string };
      if (parsed.text && parsed.filename) {
        setImported({ filename: parsed.filename, text: parsed.text });
      }
    } catch {
      /* corrupt stash — ignore */
    }
  }, []);

  function onFile(file: File | undefined) {
    if (!file) return;
    setImportErr(null);
    const reader = new FileReader();
    reader.onload = () => {
      const text = String(reader.result ?? "");
      // Quick client-side smell test: the text contains "Private key:"
      // and "Advertisement key:". Full validation happens server-side.
      if (!/private key\s*:/i.test(text) || !/advertisement key\s*:/i.test(text)) {
        setImportErr("That file doesn't look like a .keys file.");
        return;
      }
      setImported({ filename: file.name, text });
    };
    reader.onerror = () => setImportErr("Couldn't read that file.");
    reader.readAsText(file);
  }

  function toggleOwner(id: string) {
    setOwnerIds((prev) => {
      const has = prev.includes(id);
      const next = has ? prev.filter((x) => x !== id) : [...prev, id];
      if (has && primary === id) setPrimary(next[0] ?? "");
      if (!has && !primary) setPrimary(id);
      return next;
    });
  }

  const hasKeys = !!imported || showManual;
  const canSave = name.trim() && hasKeys && ownerIds.length && primary;

  return (
    <form action={formAction} style={{ display: "flex", flexDirection: "column" }}>
      {/* live preview */}
      <div
        className="edit-preview"
        style={{ flexDirection: "column", display: "flex", alignItems: "center" }}
      >
        <span
          className="drow-ico"
          style={{
            background: colorOklch(color),
            width: 64,
            height: 64,
            borderRadius: 18,
          }}
        >
          <DeviceIcon type={type} size={30} />
        </span>
        <div className="edit-prev-name">{name.trim() || "Accessory name"}</div>
      </div>

      {/* import card — primary path */}
      {!imported && (
        <button
          type="button"
          className="import-btn"
          onClick={() => fileRef.current?.click()}
        >
          <span className="import-btn-ico">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="19"
              height="19"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              aria-hidden
            >
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
              <polyline points="17 8 12 3 7 8" />
              <line x1="12" x2="12" y1="3" y2="15" />
            </svg>
          </span>
          <span className="col" style={{ flex: 1, alignItems: "flex-start" }}>
            <strong>Import from key file</strong>
            <span className="faint" style={{ fontSize: 12 }}>
              .keys generated by the firmware tools
            </span>
          </span>
          <svg
            className="drow-chev"
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2.2"
            strokeLinecap="round"
            strokeLinejoin="round"
            aria-hidden
          >
            <path d="m9 18 6-6-6-6" />
          </svg>
        </button>
      )}
      <input
        ref={fileRef}
        type="file"
        accept=".keys,.txt,text/plain"
        hidden
        onChange={(e) => onFile(e.target.files?.[0] ?? undefined)}
      />

      {imported && (
        <div
          className="drow"
          style={{
            background: "var(--accent-soft)",
            borderColor: "var(--accent)",
            color: "var(--text)",
          }}
        >
          <span
            className="drow-ico"
            style={{ background: "var(--accent)", color: "var(--on-accent)" }}
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="20"
              height="20"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.6"
              strokeLinecap="round"
              strokeLinejoin="round"
              aria-hidden
            >
              <path d="M20 6 9 17l-5-5" />
            </svg>
          </span>
          <div className="drow-main">
            <span className="drow-name">{imported.filename}</span>
            <span className="drow-sub">Key imported · ready to add</span>
          </div>
          <button
            type="button"
            onClick={() => {
              setImported(null);
              if (fileRef.current) fileRef.current.value = "";
            }}
            className="icon-btn"
            style={{ width: 32, height: 32, background: "transparent" }}
            aria-label="Remove imported key"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="14"
              height="14"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.4"
              strokeLinecap="round"
              strokeLinejoin="round"
              aria-hidden
            >
              <path d="M18 6 6 18M6 6l12 12" />
            </svg>
          </button>
        </div>
      )}

      {importErr && (
        <div className="auth-err" style={{ marginTop: 8 }}>
          {importErr}
        </div>
      )}

      {/* Manual fallback — collapsed by default */}
      {!imported && (
        <button
          type="button"
          onClick={() => setShowManual((v) => !v)}
          className="auth-hint"
          style={{
            marginTop: 8,
            background: "transparent",
            border: "none",
            cursor: "pointer",
            color: "var(--accent)",
          }}
        >
          {showManual ? "Hide manual paste" : "Or paste keyfile contents…"}
        </button>
      )}

      {!imported && showManual && (
        <>
          <label className="field-label" htmlFor="keys-manual">
            Keyfile contents
          </label>
          <textarea
            id="keys-manual"
            name="keys"
            className="text-field"
            rows={6}
            placeholder={
              "Private key: <base64>\nAdvertisement key: <base64>\nHashed adv key: <base64>"
            }
            spellCheck={false}
          />
        </>
      )}

      {/* When imported, ship the raw text via a hidden field */}
      {imported && (
        <input type="hidden" name="keys" value={imported.text} />
      )}

      <label className="field-label" htmlFor="name">
        Name
      </label>
      <input
        id="name"
        name="name"
        className="text-field"
        placeholder="e.g. House Keys"
        value={name}
        onChange={(e) => setName(e.target.value)}
        autoFocus
        required
      />

      <label className="field-label">Icon</label>
      <input type="hidden" name="type" value={type} />
      <div className="icon-grid">
        {DEVICE_TYPES.map((t) => {
          const sel = t.id === type;
          return (
            <button
              key={t.id}
              type="button"
              className={"icon-opt" + (sel ? " sel" : "")}
              style={
                sel
                  ? {
                      background: colorOklch(color),
                      borderColor: "transparent",
                      color: "#fff",
                    }
                  : undefined
              }
              onClick={() => setType(t.id)}
              aria-pressed={sel}
            >
              <DeviceIcon type={t.id} size={22} />
              <span className="icon-opt-label">{t.label}</span>
            </button>
          );
        })}
      </div>

      <label className="field-label">
        Color
        <span className="field-label-opt" style={{ color: colorOklch(color) }}>
          {color}
        </span>
      </label>
      <input type="hidden" name="color" value={color} />
      <div className="color-grid">
        {COLORS.map((c) => (
          <button
            key={c.id}
            type="button"
            className={"color-opt" + (color === c.id ? " sel" : "")}
            style={{ background: c.oklch }}
            onClick={() => setColor(c.id)}
            title={c.label}
            aria-label={c.label}
            aria-pressed={color === c.id}
          >
            {color === c.id && (
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="18"
                height="18"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2.6"
                strokeLinecap="round"
                strokeLinejoin="round"
                aria-hidden
              >
                <path d="M20 6 9 17l-5-5" />
              </svg>
            )}
          </button>
        ))}
      </div>

      <label className="field-label">Who can locate this?</label>
      <input type="hidden" name="primaryOwnerId" value={primary} />
      <div className="owner-pick">
        {members.map((m) => {
          const on = ownerIds.includes(m.id);
          const isP = primary === m.id;
          return (
            <div key={m.id} className={"owner-pick-row" + (on ? " on" : "")}>
              <button
                type="button"
                className="opick-main"
                onClick={() => toggleOwner(m.id)}
              >
                <span
                  className="avatar sm"
                  style={{ background: colorOklch(m.color) }}
                >
                  {m.initials}
                </span>
                <div className="col">
                  <strong>{m.name}</strong>
                  {m.title && (
                    <span className="faint" style={{ fontSize: 12 }}>
                      {m.title}
                    </span>
                  )}
                </div>
                <span className={"check-box" + (on ? " on" : "")}>
                  {on && (
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="14"
                      height="14"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="3"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      aria-hidden
                    >
                      <path d="M20 6 9 17l-5-5" />
                    </svg>
                  )}
                </span>
              </button>
              {on && (
                <button
                  type="button"
                  className={"primary-toggle" + (isP ? " on" : "")}
                  onClick={() => setPrimary(m.id)}
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="13"
                    height="13"
                    viewBox="0 0 24 24"
                    fill={isP ? "currentColor" : "none"}
                    stroke="currentColor"
                    strokeWidth="2.2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    aria-hidden
                  >
                    <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
                  </svg>
                  {isP ? "Primary" : "Set primary"}
                </button>
              )}
              {on && <input type="hidden" name="owners" value={m.id} />}
            </div>
          );
        })}
      </div>
      <p className="field-help">
        The primary owner is responsible for the accessory. Others listed can
        see its location.
      </p>

      {state.message && (
        <div className="auth-err" style={{ marginTop: 12 }}>
          {state.message}
        </div>
      )}

      <button
        type="submit"
        className="btn"
        disabled={pending || !canSave}
        style={{ marginTop: 20 }}
      >
        {pending ? "Adding…" : "Add accessory"}
      </button>
    </form>
  );
}
