/**
 * FindMy report decryption.
 *
 * Each location report from Apple's /acsnservice/fetch endpoint is
 * encrypted with a fresh keypair generated by the finder iPhone.
 * The owner derives the same AES-GCM key via ECDH on P-224.
 *
 * Pipeline (matches biemster/FindMy/request_reports.py):
 *   payload (base64) = ephemeral_pub_compressed(57B) || ct(N B) || tag(16B)
 *   where ephemeral_pub starts with a 4-byte timestamp then byte 0x05 prefix
 *
 *   shared        = ECDH(privateKey, ephemeral_pub).x       (28 B)
 *   symmetric_key = SHA-256(shared || 0x00000001 || ephemeral_pub_compressed)
 *   enc_key       = symmetric_key[0..16]
 *   iv            = symmetric_key[16..32]
 *   plaintext     = AES-128-GCM-decrypt(enc_key, iv, ct, tag)
 *
 *   plaintext layout (10 bytes):
 *     lat (s32 big-endian) / 1e7
 *     lng (s32 big-endian) / 1e7
 *     confidence (u8)
 *     status     (u8)
 */
import { createDecipheriv, createECDH, createHash } from "node:crypto";

export interface DecryptedReport {
  lat: number;
  lng: number;
  confidence: number;
  status: number;
  timestamp: number; // seconds since epoch
}

const APPLE_EPOCH_OFFSET = 978307200; // seconds between 1970-01-01 and 2001-01-01

function sha256(...chunks: Uint8Array[]): Buffer {
  const h = createHash("sha256");
  for (const c of chunks) h.update(c);
  return h.digest();
}

/**
 * Decrypt one report's `payload` (base64 from Apple) using the
 * accessory's private key (28-byte big-endian P-224 scalar).
 */
export function decryptReport(payloadB64: string, privateKey: Buffer): DecryptedReport {
  // Apple sometimes hands back 88-byte payloads, sometimes 89; the older
  // protocol includes an extra status byte at index 4 that needs to be
  // stripped. biemster's heuristic is `if len(data) > 88: data = data[:4] + data[5:]`.
  let data = Buffer.from(payloadB64, "base64");
  if (data.length > 88) {
    data = Buffer.concat([data.subarray(0, 4), data.subarray(5)]);
  }

  // First 4 bytes are an Apple-epoch seconds timestamp.
  const timestamp = data.readUInt32BE(0) + APPLE_EPOCH_OFFSET;

  // Bytes [5..62) are the finder iPhone's uncompressed P-224 public key
  // (57 bytes: 0x04 prefix + 28-byte X + 28-byte Y). data[62..end-16] = ciphertext.
  // data[last 16] = AES-GCM tag.
  const ephPubUncompressed = data.subarray(5, 62);
  const ct = data.subarray(62, data.length - 16);
  const tag = data.subarray(data.length - 16);

  // ECDH on P-224 via Node's built-in crypto. computeSecret returns the
  // raw X coordinate of the shared point (28 bytes), no prefix.
  const ecdh = createECDH("secp224r1");
  ecdh.setPrivateKey(privateKey);
  const sharedX = ecdh.computeSecret(ephPubUncompressed);

  // ANSI X9.63 KDF: SHA-256(shared || 0x00 0x00 0x00 0x01 || ephPubUncompressed)
  const symmetric = sha256(sharedX, Buffer.from([0, 0, 0, 1]), ephPubUncompressed);
  const encKey = symmetric.subarray(0, 16);
  const iv = symmetric.subarray(16, 32);

  const decipher = createDecipheriv("aes-128-gcm", encKey, iv);
  decipher.setAuthTag(tag);
  const plain = Buffer.concat([decipher.update(ct), decipher.final()]);

  const lat = plain.readInt32BE(0) / 1e7;
  const lng = plain.readInt32BE(4) / 1e7;
  const confidence = plain.readUInt8(8);
  const status = plain.readUInt8(9);

  return { lat, lng, confidence, status, timestamp };
}
